### PR TITLE
Add mouse support

### PR DESCRIPTION
**Pull request by yosinda**
Supports PC-8872 compatible mouse. (aka "bus mouse")

To enable it, connect a USB mouse to MiSTer, and select "Mouse" in the "Input" of the F12 menu.
The mouse cannot be enabled at the same time as the joypad.
(default: Joypad)

### CODE REVIEW

**Comment by wwark** [comment]
thank you ;)

**Comment by wwark** [comment]
@yosinda since this PR, I have issue to launch Xak and some others games.

**Comment by yosinda** [comment]
I tried the unstable build built with this PR commit, but the problem did not regenerated.
(PC88_unstable_20240726_16ce86.rbf)
I hope your DE10 isn't broken...

https://github.com/MiSTer-unstable-nightlies/PC88_MiSTer/releases/download/unstable-builds/PC88_unstable_20240726_16ce86.rbf

**Comment by wwark** [comment]
Thank you for your quick return.

I tried to compile https://github.com/MiSTer-devel/PC88_MiSTer/commit/ccd6f69c6d45771547a57376d91ee5e13c9463f5 and it works I can load floppies and it goes in game.
But if I tried the unstable build (26/07 or 31/07) it doesn't work, it returns every test to basic.
I will tried to compile https://github.com/MiSTer-devel/PC88_MiSTer/commit/e382092ff9bec382df5beba0dfe3987ce83d86ec

**Comment by wwark** [comment]
Yes the issue happens with this commit https://github.com/MiSTer-devel/PC88_MiSTer/commit/e382092ff9bec382df5beba0dfe3987ce83d86ec
I have an old version of SDRAM v2.5 or v2.4 (2019) so maybe it is related to my SDRAM

**Comment by yosinda** [comment]
I am using SDRAM v2.9.
Maybe the change in commit e382092 was bad and changed the tool's delay calculations?
Unfortunately I can't think of a way to fix this now.

**Pull request merged**
